%According the datas, some talbes are generated by using procedure.

algorithms = ["MI","SGEA","PPS","DNSGAIIA","DNSGAIIB"];  % all compared algorithms. 

%Each test problem includes the number of results. For example, "1020"
%refers that the severity of change is set to 10, and the frequency of
%change is set to 20.
results = ["1010", "1020", "1030"]; 

metrics ="IGD";
input =".\result\" +metrics+".dat";

data;
%get all data to generate table.
for i = 1 :  size(algorithms,2)
    for j = 1 : size(results,2)
       
        str = ".\data\"+algorithms(i)+"\"+results(j)+ "\evaluate\statistics\"+metrics+".dat"
        A=importdata(str);
        
        data(i,j) = A;
        
    end;
end;

%save the date into the file.

fid = fopen(input,'w');
for i = 1 :  size(algorithms,2)
    for j = 1 : size(results,2)
       
       out = data(i,j).data
       %fprintf(fid,'% g\n',data(i,j).data);
        
    end;
end;


